In documentation, value labels are:

1	A great deal of confidence
2	A fair amount of confidence
3	Not too much confidence
4	No confidence at all
99	Don't know/Refused/Web blank

Therefore, will reverse code

In [1]:
import pandas as pd

df = pd.read_csv(r'..\data\W158_select_nan.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   QKEY                  9593 non-null   int64
 1   CONF_a_W158           9564 non-null   float64
 2   CONF_b_W158           9580 non-null   float64
 3   CONF_c_W158           9575 non-null   float64
 4   CONF_d_W158           9568 non-null   float64
 5   CONF_e_W158           9573 non-null   float64
 6   CONF_i_W158           9568 non-null   float64
 7   CONF_j_W158           9581 non-null   float64
 8   F_METRO               9585 non-null   float64
 9   F_CREGION             9585 non-null   float64
 10  F_CDIVISION           9585 non-null   float64
 11  F_USR_SELFID          9493 non-null   float64
 12  F_AGECAT              9555 non-null   float64
 13  F_GENDER              9561 non-null   float64
 14  F_EDUCCAT             9572 non-null   float64
 15  F_EDUCCAT2            9572 non-null   float64
 16  F_HISP                9565 non-null   float64
 17  F_RACECMB             9449 non-null   float64
 18  F_RACETHNMOD          9491 non-null   float64
 19  F_BIRTHPLACE          9551 non-null   float64
 20  F_MARITAL             9548 non-null   float64
 21  F_RELIG               9536 non-null   float64
 22  F_PARTY_FINAL         9534 non-null   float64
 23  F_PARTYSUM_FINAL      9392 non-null   float64
 24  F_PARTYSUMIDEO_FINAL  9295 non-null   float64
 25  F_INC_SDT1            5722 non-null   float64
 26  F_IDEO                9447 non-null   float64
 27  F_INC_TIER2           9006 non-null   float64
 28  WEIGHT_W158           9593 non-null   float64
dtypes: float64(28), int64(1)
memory usage: 2.1 MB

In [2]:
dep_var_list = [
    'CONF_a_W158',
    'CONF_b_W158',
    'CONF_c_W158',
    'CONF_d_W158',
    'CONF_e_W158',
    'CONF_i_W158',
    'CONF_j_W158'
    ]

print(dep_var_list)

['CONF_a_W158', 'CONF_b_W158', 'CONF_c_W158', 'CONF_d_W158', 'CONF_e_W158', 'CONF_i_W158', 'CONF_j_W158']

In [3]:
#Rename variables

df = df.join(df[dep_var_list].add_suffix("_r"))

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   QKEY                  9593 non-null   int64
 1   CONF_a_W158           9564 non-null   float64
 2   CONF_b_W158           9580 non-null   float64
 3   CONF_c_W158           9575 non-null   float64
 4   CONF_d_W158           9568 non-null   float64
 5   CONF_e_W158           9573 non-null   float64
 6   CONF_i_W158           9568 non-null   float64
 7   CONF_j_W158           9581 non-null   float64
 8   F_METRO               9585 non-null   float64
 9   F_CREGION             9585 non-null   float64
 10  F_CDIVISION           9585 non-null   float64
 11  F_USR_SELFID          9493 non-null   float64
 12  F_AGECAT              9555 non-null   float64
 13  F_GENDER              9561 non-null   float64
 14  F_EDUCCAT             9572 non-null   float64
 15  F_EDUCCAT2            9572 non-null   float64
 16  F_HISP                9565 non-null   float64
 17  F_RACECMB             9449 non-null   float64
 18  F_RACETHNMOD          9491 non-null   float64
 19  F_BIRTHPLACE          9551 non-null   float64
 20  F_MARITAL             9548 non-null   float64
 21  F_RELIG               9536 non-null   float64
 22  F_PARTY_FINAL         9534 non-null   float64
 23  F_PARTYSUM_FINAL      9392 non-null   float64
 24  F_PARTYSUMIDEO_FINAL  9295 non-null   float64
 25  F_INC_SDT1            5722 non-null   float64
 26  F_IDEO                9447 non-null   float64
 27  F_INC_TIER2           9006 non-null   float64
 28  WEIGHT_W158           9593 non-null   float64
 29  CONF_a_W158_r         9564 non-null   float64
 30  CONF_b_W158_r         9580 non-null   float64
 31  CONF_c_W158_r         9575 non-null   float64
 32  CONF_d_W158_r         9568 non-null   float64
 33  CONF_e_W158_r         9573 non-null   float64
 34  CONF_i_W158_r         9568 non-null   float64
 35  CONF_j_W158_r         9581 non-null   float64
dtypes: float64(35), int64(1)
memory usage: 2.6 MB

In [4]:
dep_var_list_r = [
    'CONF_a_W158_r',
    'CONF_b_W158_r',
    'CONF_c_W158_r',
    'CONF_d_W158_r',
    'CONF_e_W158_r',
    'CONF_i_W158_r',
    'CONF_j_W158_r'
    ]

print(dep_var_list_r)

['CONF_a_W158_r', 'CONF_b_W158_r', 'CONF_c_W158_r', 'CONF_d_W158_r', 'CONF_e_W158_r', 'CONF_i_W158_r', 'CONF_j_W158_r']

In [5]:
# Recode

mapping = {1.0: 4.0, 2.0: 3.0, 3.0: 2.0, 4.0: 1.0}
df[dep_var_list_r] = df[dep_var_list_r].replace(mapping)

In [6]:
df[dep_var_list].head()

,CONF_a_W158,CONF_b_W158,CONF_c_W158,CONF_d_W158,CONF_e_W158,CONF_i_W158,CONF_j_W158
0,3.0,3.0,2.0,3.0,2.0,2.0,1.0
1,3.0,2.0,1.0,1.0,3.0,1.0,1.0
2,4.0,4.0,3.0,2.0,3.0,2.0,2.0
3,2.0,2.0,1.0,2.0,1.0,1.0,1.0
4,3.0,4.0,2.0,2.0,3.0,3.0,2.0

In [7]:
df[dep_var_list_r].head()

,CONF_a_W158_r,CONF_b_W158_r,CONF_c_W158_r,CONF_d_W158_r,CONF_e_W158_r,CONF_i_W158_r,CONF_j_W158_r
0,2.0,2.0,3.0,2.0,3.0,3.0,4.0
1,2.0,3.0,4.0,4.0,2.0,4.0,4.0
2,1.0,1.0,2.0,3.0,2.0,3.0,3.0
3,3.0,3.0,4.0,3.0,4.0,4.0,4.0
4,2.0,1.0,3.0,3.0,2.0,2.0,3.0

In [8]:
df["CONF_a_W158"].value_counts().sort_index(ascending=True)

CONF_a_W158
1.0     173
2.0    3084
3.0    4977
4.0    1330
Name: count, dtype: int64

In [9]:
df["CONF_a_W158_r"].value_counts().sort_index(ascending=True)

CONF_a_W158_r
1.0    1330
2.0    4977
3.0    3084
4.0     173
Name: count, dtype: int64

In [10]:
df_r = df.drop(columns=dep_var_list)
df_r.info()

<class 'pandas.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   QKEY                  9593 non-null   int64
 1   F_METRO               9585 non-null   float64
 2   F_CREGION             9585 non-null   float64
 3   F_CDIVISION           9585 non-null   float64
 4   F_USR_SELFID          9493 non-null   float64
 5   F_AGECAT              9555 non-null   float64
 6   F_GENDER              9561 non-null   float64
 7   F_EDUCCAT             9572 non-null   float64
 8   F_EDUCCAT2            9572 non-null   float64
 9   F_HISP                9565 non-null   float64
 10  F_RACECMB             9449 non-null   float64
 11  F_RACETHNMOD          9491 non-null   float64
 12  F_BIRTHPLACE          9551 non-null   float64
 13  F_MARITAL             9548 non-null   float64
 14  F_RELIG               9536 non-null   float64
 15  F_PARTY_FINAL         9534 non-null   float64
 16  F_PARTYSUM_FINAL      9392 non-null   float64
 17  F_PARTYSUMIDEO_FINAL  9295 non-null   float64
 18  F_INC_SDT1            5722 non-null   float64
 19  F_IDEO                9447 non-null   float64
 20  F_INC_TIER2           9006 non-null   float64
 21  WEIGHT_W158           9593 non-null   float64
 22  CONF_a_W158_r         9564 non-null   float64
 23  CONF_b_W158_r         9580 non-null   float64
 24  CONF_c_W158_r         9575 non-null   float64
 25  CONF_d_W158_r         9568 non-null   float64
 26  CONF_e_W158_r         9573 non-null   float64
 27  CONF_i_W158_r         9568 non-null   float64
 28  CONF_j_W158_r         9581 non-null   float64
dtypes: float64(28), int64(1)
memory usage: 2.1 MB

In [11]:
df_r.to_csv(r'..\data\W158_select_nan_recode.csv', index=False)